### PR TITLE
Korean Update

### PR DESCRIPTION
**Pull request by eraracom**
Project-Id-Version: Modelica by Example v0.3.6
report-Msgid-Bugs-To: mail@modelica.co.kr
POT-Creation-Date: 2023-01-28 22:37+0000
PO-Revision-Date: 2023-03-12 22:37+0000
Last-Translator: Baek Youngjin, mail@modelica.co.kr / Ha HyeonSu, <iloveyou934671@gmail.com>
Language-Team: modelica.co.kr <mail@modelica.co.k>

### CODE REVIEW

**Review by mtiller — APPROVED** [review]
Looks good as far as I can tell.  I'm a little worried that the English text looks a bit different in the `.po` files but I'm assuming this is because it changed since I first generated the `.po` files.  I'm not sure what issues I'll have trying to incorporate these translations, but I need to accept this as the first step and then deal with whatever issues crop up after that.

**Comment by eraracom** [comment]
Dear. Michael Tiller.

Greetings for the day!
Thank you for your merge.

I will find other parts and rewrite them soon.
And we will re examine everything.
Thank you for your kindness.



2023년 8월 30일 (수) 오전 5:12, Michael Tiller ***@***.***>님이 작성:

**Comment by mtiller** [comment]
@eraracom Thank you for having written the translations and my apologies that it took me so long to merge the changes.  I have been working over the past two weeks to try and get this repository into better shape.  I now have a new tool chain and CI process in place that is able to build the book (English and Korean).  I will send you some updates soon on how this works.  My goal is that you should be able to submit additional changes and trigger builds that give you direct feedback on any issues that are found and to provide you with previews of the web site as well.  Hopefully I can get all that working by next week.  I will let you know as soon as things are working well.

Thanks again for your partience.

**Comment by mtiller** [comment]
@eraracom I'm still working on automation related steps, but I just wanted to share with you the Korean version of the site which I have managed to deploy:

https://sparkly-praline-51a243.netlify.app/kr/

The URL will change, this is just temporary while I work on the automation.

**Comment by mtiller** [comment]
@eraracom Have you had a chance to review the Korean content?  Are you comfortable with me releasing this on my site?

**Pull request merged**
