### PR TITLE
initialization of overdetermined systems

### PR DESCRIPTION
**Pull request by lochel**
In the meantime, there have been several approaches developed to handle overdetermined initialization problems. So I think the note regarding overdetermined initialization problems should be removed or replaced by something appropriate.

### CODE REVIEW

**Comment by xogeny** [comment]
I think both sentences should be present.  They are really addressing two different things.  If there aren't enough, equations, the results are unpredictable.  If there are too many, no solution exists.

**Comment by lochel** [comment]
That's just wrong. If there are too many equations it could either be that no solution exists or that there is some redundancy which a tool may remove, e.g. OpenModelica does this.

**Comment by lochel** [comment]
Together with @casella, we developed a prototype to handle this kind of problems. In the meantime, things have improved a lot and the current approach is not really reflected by that early prototype, however it is solvable in many cases. You can find out paper from the 10th Modelica conference [here](http://www.ep.liu.se/ecp/096/124/ecp14096124.pdf).

**Comment by harmanpa** [comment]
Dymola, SimulationX and CyModelica all also allow overdetermined initialisation by removing redundant equations and checking they are consistent. From a tool-neutral point of view though it should be clear that models with balanced initial equations are the "correct" solution as it will give consistent results, but tools may help the user by solving the other cases.

**Comment by xogeny** [comment]
Part of the confusion here is terminology.  When I use a term like "overdetermined", I mean that these "extra" equations are not redundant.  If there are extra equations but the problem is still full rank, then I don't consider that "overdetermined".

But that is also beside the point.  I agree that one could point out at this point in the book that some tools will help to identify redundant equations and eliminate them.  But I am hesitant to include such language for several reasons:

- Support is uneven.  Even among tools that do this, they may do it in different ways.
- It is a crutch.  Better is to ensure that the initialize problem is full rank without depending on such functionality.  Sure, this may be difficult to do in large projects or with optimal flexibility.  But that is more about the professional business of modeling, not the physical or mathematical aspects.
- People might easily get confused by even bringing up such technical details at this point in the book.
- The book is about the language, not the tools.  While I can appreciate the effort that it takes to implement this functionality, the goal at this point in the book is to focus on helping people learn rather than brag about features of specific tools.  Discussions on these topics only serve to steepen the learning curve with no real benefit to the reader.

As such, I feel like the emphasis here should be on making the initialization problem well posed with warnings about the consequences of under-determined systems.  The only thing I think it would be appropriate to say here regarding the overdetermined aspect would be something along the lines of "In general, having more initial equations that states will cause the initialization to fail (although some tools may still manage to find a valid solution)".

**Comment by lochel** [comment]
I see this somewhat differently: In general, I would say having too less initial equations is most likely a modeling issue, whereas having too many initial equations is something that may happen due to the language concepts (or due to a modelling issue). That means:

* I would strongly recommend to any new Modelica user to avoid having too less initial conditions.
* A discussion about too many initial conditions should be part of a chapter about higher-index models. However, a short statement might be reasonable at this point anyway.

**Comment by casella** [comment]
The usual source of overdetermined but otherwise consistent initializatio problem is index reduction. My point has always been that index reductio does happen often in Modelica models, that it makes some initial equations redundant, and that tools should be able to handle that automatically. I agree with @lochel that this topic is closely related to high-index systems.

**Comment by dietmarw** [comment]
So what about simply changing the sentence in this way:

```diff
- provide with additional ones until the problem is well-posed, but we
- cannot solve a problem where we have too many initial equations.
+ provide with additional ones until the problem is well-posed, but we
+ may not be able to solve a problem where we have too many initial equations.
```
This would be a good compromise in my opinion.

**Comment by xogeny** [comment]
Seems there is agreement on the proposed change.  I'm scheduling this for `0.6.0` since we are trying to push `0.5.0` out the door and I don't want to delay.  But this is an easy change and I'll definitely add this after `0.5.0` is published.

**Pull request closed without merging**
